// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDdjrBMqgBi4Yt1l-1edRCi9AmaJpnYw',
    appId: '1:662716801122:web:8c5dcd663add5f88b7f13b',
    messagingSenderId: '662716801122',
    projectId: 'flutter-crud-210cc',
    authDomain: 'flutter-crud-210cc.firebaseapp.com',
    storageBucket: 'flutter-crud-210cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9C7C4BGQQaaZw4ARvDNBGfSQYUf05vY',
    appId: '1:662716801122:android:9b5c27d38646d674b7f13b',
    messagingSenderId: '662716801122',
    projectId: 'flutter-crud-210cc',
    storageBucket: 'flutter-crud-210cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7n8SsO2t0FFZoTs46_kbvDhkN5uN2r_E',
    appId: '1:662716801122:ios:392a8c500ed0da9eb7f13b',
    messagingSenderId: '662716801122',
    projectId: 'flutter-crud-210cc',
    storageBucket: 'flutter-crud-210cc.firebasestorage.app',
    iosBundleId: 'com.example.productsManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7n8SsO2t0FFZoTs46_kbvDhkN5uN2r_E',
    appId: '1:662716801122:ios:392a8c500ed0da9eb7f13b',
    messagingSenderId: '662716801122',
    projectId: 'flutter-crud-210cc',
    storageBucket: 'flutter-crud-210cc.firebasestorage.app',
    iosBundleId: 'com.example.productsManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWDdjrBMqgBi4Yt1l-1edRCi9AmaJpnYw',
    appId: '1:662716801122:web:68834efbc9f36a7cb7f13b',
    messagingSenderId: '662716801122',
    projectId: 'flutter-crud-210cc',
    authDomain: 'flutter-crud-210cc.firebaseapp.com',
    storageBucket: 'flutter-crud-210cc.firebasestorage.app',
  );
}